### ISSUE TITLE
investigate htcondorcern compute backend troubles

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-workflow-engine-snakemake#27]
Follow-up from https://github.com/reanahub/reana-demo-helloworld/pull/58

The demo workflow runs well on `slurmcern` compute backend, but `htcondorcern` compute backend leads to:

```console
$ reana-client logs -w helloworld-snakemake-htcondorcern
...
2021-10-19 07:48:03,654 | reana-workflow-engine-snakemake | MainThread | ERROR | Error submitting job helloworld: Expecting value: line 1 column 1 (char 0)
2021-10-19 07:48:03,657 | reana-workflow-engine-snakemake | MainThread | INFO | failed job: None
```

We should investigate and fix the problem.

**Comment by tiborsimko** [comment]
From another demo workflow, here is the job controller exception:

```console
$ kubectl logs reana-run-batch-xxx job-controller
...
2021-10-19 08:09:08,213 | reana_job_controller.factory | Thread-2 | ERROR | Exception on /jobs [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/reana_job_controller/rest.py", line 228, in create_job
    backend_jod_id = job_obj.execute()
  File "/usr/local/lib/python3.8/site-packages/reana_job_controller/job_manager.py", line 64, in wrapper
    backend_job_id = fn(inst, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/reana_job_controller/htcondorcern_job_manager.py", line 125, in execute
    job_ad["Arguments"] = self._format_arguments()
  File "/usr/local/lib/python3.8/site-packages/reana_job_controller/htcondorcern_job_manager.py", line 185, in _format_arguments
    base64.b64encode(base_cmd.encode("utf-8")).decode("utf-8")
UnboundLocalError: local variable 'base_cmd' referenced before assignment
```
